version: '3'

volumes:
  db_data:
  wordpress_data:
#  wordpress_themes:
#  wordpress_plugins:

services:

  # - 

  db:
    image: bitnami/mariadb:latest
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
        #- "MARIADB_ROOT_USER=$ABW_DB_ROOT_USER"
        #- "MARIADB_ROOT_PASSWORD=$ABW_DB_ROOT_PASSWORD"
      - "MARIADB_DATABASE=wordpress"
      - "MARIADB_USER=abw_db_user"
      - "MARIADB_PASSWORD=$ABW_DB_PASSWORD"
    expose:
      - 3306
    volumes:
            - db_data:/bitnami/mariadb/data:cached
    networks:
      - net

  # - 

  wordpress:
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
            #- "MARIADB_ROOT_USER=$ABW_DB_ROOT_USER"
            #- "MARIADB_ROOT_PASSWORD=$ABW_DB_ROOT_PASSWORD"
      - "MARIADB_HOST=db"
      - "MARIADB_PORT_NUMBER=3306"
      - "WORDPRESS_DATABASE_NAME=wordpress"
      - "WORDPRESS_DATABASE_USER=abw_db_user"
      - "WORDPRESS_DATABASE_PASSWORD=$ABW_DB_PASSWORD"
      - "WORDPRESS_BLOG_NAME=abw-site"
      - "WORDPRESS_FIRST_NAME="
      - "WORDPRESS_LAST_NAME="
      - "WORDPRESS_USERNAME=abw-user"
      - "WORDPRESS_PASSWORD=$ABW_WORDPRESS_PASSWORD"
      - "WORDPRESS_EMAIL=$ABW_GMAIL_EMAIL"
        #- "SMTP_HOST=smtp.gmail.com"
        #- "SMTP_PORT=587"
        #- "SMTP_USER=$ABW_GMAIL_EMAIL"
        #- "SMTP_PASSWORD=$ABW_GMAIL_PASSWORD"
        #- "SMTP_PROTOCOL=tls"
    volumes:
      - wordpress_data:/bitnami:cached
      - ../../.tmp/backups:/backups:cached
    networks:
      - net
    depends_on:
      - db

networks:
  net: 
